name: Byrd pro api
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    name: test code
    env:
      GO_VERSION: 1.14

    steps:
      - name: Check out master branch
        uses: actions/checkout@master

      - name: Verify Go version
        run: echo Go runnning on $GO_VERSION

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14 # The Go version to download (if necessary) and use.
        id: go

      - name: Go vet
        run: go vet cmd/byrd-pro-api/main.go

      - name: List Files
        run: ls -alrt $GITHUB_WORKSPACE

      # - name: Go test
      #   run: go test

  build:
    name: build code
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@master
      - name: Build the Docker image
        run: |
          docker build --rm -f "Dockerfile" -t byrdapp/pro-api:dev .
          docker build --rm -f "Dockerfile" -t byrdapp/pro-api:prod .

      - name: Login to DockerHub registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker dev image to the registry
        run: docker push byrdapp/pro-api:dev

      - name: Push the Docker prod image to the registry
        run: docker push byrdapp/pro-api:prod

  slack:
    name: Notify on slack
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@master

      - name: Notify slack
        # uses: pullreminders/slack-action@master
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
          SLACK_USERNAME: SweetBabyRays
          SLACK_CHANNEL: "#deployments"
          SLACK_COLOR: "#517122"
          SLACK_ICON: https://avatars0.githubusercontent.com/u/7809248?s=400&v=4
          SLACK_TITLE: "New pro api ready to be swarmed!"
          SLACK_MESSAGE: "This will be awesome!"
